### ISSUE TITLE
Dependent field refinements dropped when using field accessor functions

### ISSUE THREAD

**Issue by Gabriel439** [ucsd-progsys/liquidhaskell#595]
The following program correctly type-checks:

```haskell
import Data.Vector

{-@
data Test = Test
    { v  :: Vector ()
    , x0 :: { x0 : Bool | vlen v < 1 ==> Prop x0 }
    }
@-}

data Test = Test
    { v  :: Vector ()
    , x0 :: Bool
    }

example :: Test -> ()
example (Test v_ x0_) =
    if x0_
    then ()
    else v_ ! 0
```

However, if I change `example` to use field accessors instead of pattern matching on the constructor then the program fails to type-check:

```haskell
import Data.Vector

{-@
data Test = Test
    { v  :: Vector ()
    , x0 :: { x0 : Bool | vlen v < 1 ==> Prop x0 }
    }
@-}

data Test = Test
    { v  :: Vector ()
    , x0 :: Bool
    }

example :: Test -> ()
example t =
    if x0 t
    then ()
    else v t ! 0
```

**Comment by gridaphobe** [comment]
Interesting example, thanks!

I suspect the problem is that in the second example you have

```
x0 t :: {x0 : Bool | vlen v < 1 ==> Prop x0}
```

but `v` is not in scope, so we drop the refinement.

The fix would be for us to automatically change the type of `x0` (the field accessor) to

```
x0 :: t:Test -> {x0:Bool | vlen (v t) < 1 ==> Prop x0}
```

i.e. treat `v` as a field accessor as well.

**Comment by ranjitjhala** [comment]
@gridaphobe in the second case `v` _is_ in scope, it is the other field...

**Comment by gridaphobe** [comment]
In the second `example`, the `v` field is **not** in scope, there's no case analysis.

**Comment by ranjitjhala** [comment]
Right, the issue is that I think the field accessors are not getting the right strengthened types, which, in this case should be:

``` haskell

import Data.Vector

{-@
data Test = Test
    { v  :: Vector ()
    , x0 :: { x0 : Bool | vlen v < 1 ==> Prop x0 }
    }
@-}

{-@ get_v :: t:Test -> {r:_ | r == v t} @-}
get_v  :: Test -> Vector ()
get_v (Test a _) = a

{-@ get_x0 :: t:Test -> {r:_ | r == x0 t && (vlen (v t) < 1 ==> Prop r) } @-}
get_x0 :: Test -> Bool
get_x0 (Test _ a) = a


data Test = Test
    { v  :: Vector ()
    , x0 :: Bool
    }

example :: Test -> ()
example t =
    if get_x0 t
    then ()
    else get_v t ! 0
```

if we use the above (i've renamed the accessors to `get_`) then it is properly verified.

@nikivazou -- I think the fix here is to strengthen the output types of the accessors as shown above.

Right?

**Comment by ranjitjhala** [comment]
@Gabriel439 -- thanks again for pointing this out!

**Comment by nikivazou** [comment]
Correct @ranjitjhala! 

You do not even need to define new functions you just need to refine the existing accessors, see http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1453934384_993.hs

Just add two signatures that relate the logical with the Haskell functions:

```
{-@ v :: t:Test -> {r:_   | r == v t}    @-}
{-@ x0 :: t:Test -> {r:_ | r == x0 t } @-}
```


PS: I believe I have implemented this to happen automatically, did anyone turn it off?

**Comment by ranjitjhala** [comment]
@nikivazou

1. Can you remind me again why we need to write the two signatures
   (i.e. for  `v` and `x0`) ?
   Was there a reason they cannot be auto generated?


2. Your example is still not quite right, because, e.g. the following
breaks:

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1453936423_997.hs

   Your version requires unpacking the `t` with `_` (which effectively
   brings binders into scope. My proposal is to eliminate the need for those
   binders altogether by replacing the corresponding fields with
   measure applications.

**Comment by nikivazou** [comment]
Oups, sorry, I forgot that I edited the test to bring binders in scope...

I tried your approach and it is unsafe: 
http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1453954794_1018.hs

My only comment on @ranjitjhala's example is that you do not need to define the getters (get_x0, get_v).  The definitions you provide are exactly the ones auto generated internally for the field selectors. So, you can instead just specify refined signatures for the selectors (`x0` and `v`).

Well, from this issue, it seems that we do not automatically refine the signatures of the field selectors because it is not clear how to refine them...

**Comment by gridaphobe** [comment]
As discussed on slack, the refined selector types **do** in fact work.

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1453956403_1038.hs

The problem was with a misunderstanding of the relative precedences of `&&` and `=>` :)

**Comment by gridaphobe** [comment]
This is fixed by #654

**Comment by ranjitjhala** [comment]
Thanks @gridaphobe!

**Comment by Gabriel439** [comment]
Thank you!
