### ISSUE TITLE
Generic measure specialization appears to remain unused

### ISSUE THREAD

**Issue by j6carey** [ucsd-progsys/liquidhaskell#649]
With a file `t.hs` containing:
```haskell
module T where

import Data.Proxy
import Data.Word

{-@ class measure sizeOf :: forall a . Proxy a -> Int @-}
{-@
instance measure sizeOf :: Proxy Word16 -> Int
sizeOf (Proxy) = 2
@-}
{-@
instance measure sizeOf :: Proxy Word32 -> Int
sizeOf (Proxy) = 4
@-}

{-@
bar :: { x : Int | x = (sizeOf (Proxy :: Proxy Word32)) }
    -> ()
@-}
bar :: Int -> ()
bar _ = ()

{-@
qux :: { x : Int | x = 4 }
    -> ()
@-}
qux :: Int -> ()
qux = bar
```

I see this incorrect error:
```
$ stack exec liquid -- t.hs
LiquidHaskell Copyright 2009-15 Regents of the University of California. All Rights Reserved.


**** DONE:  Cleaned Files ******************************************************
 

**** DONE:  Parsed All Specifications ******************************************
 

**** DONE:  Loaded Targets *****************************************************
 

**** DONE:  Extracted Core using GHC *******************************************
 

**** DONE:  generateConstraints ************************************************
 
Working   0% [.................................................................]
Done solving.

**** DONE:  solve **************************************************************
 

**** DONE:  annotate ***********************************************************
 

**** RESULT: UNSAFE ************************************************************


 t.hs:28:7-9: Error: Liquid Type Mismatch
 
 28 | qux = bar
            ^^^
 
   Inferred type
     VV : {VV : (GHC.Types.Int <>) | VV == 4}
  
   not a subtype of Required type
     VV : {VV : (GHC.Types.Int <>) | VV == sizeOf (Data.Proxy.Proxy : (Data.Proxy.Proxy  GHC.Word.Word32))}
  
   In Context
$
```

**Comment by ranjitjhala** [comment]
Could this have to do with the recently fixed Word literal issue..?

**Comment by gridaphobe** [comment]
I think the problem is not so much that the instance measure is unused, but that we don't support type ascriptions in refinements, ie we don't support the

```
Proxy :: Proxy Word32
```

expression. I'm honestly surprised that it even parses.

**Comment by j6carey** [comment]
Here is a variant that does not use `Proxy :: Proxy Word32`:
```haskell
module T where

import Data.Proxy
import Data.Word
import GHC.Ptr

{-@ class measure sizeOf :: forall a . Data.Proxy.Proxy a -> Int @-}
{-@
instance measure sizeOf :: (Data.Proxy.Proxy Data.Word.Word16) -> Int
sizeOf (Proxy) = 2
@-}
{-@
instance measure sizeOf :: (Data.Proxy.Proxy Data.Word.Word32) -> Int
sizeOf (Proxy) = 4
@-}

{-@
measure ptrToProxy :: forall a . Ptr a -> (Proxy a)
ptrToProxy (Ptr a) = Proxy
@-}

{-@
bar :: { p : Ptr Word32 | plen p >= (sizeOf (ptrToProxy p)) }
    -> ()
@-}
bar :: Ptr Word32 -> ()
bar _ = ()

{-@
qux :: { p : Ptr Word32 | plen p >= 4 }
    -> ()
@-}
qux :: Ptr Word32 -> ()
qux = bar
```

The output:
```
...
**** RESULT: UNSAFE ************************************************************


 t.hs:34:7-9: Error: Liquid Type Mismatch
 
 34 | qux = bar
            ^^^
 
   Inferred type
     VV : {VV : (GHC.Ptr.Ptr <> (GHC.Word.Word32 <>)) | plen VV >= 4}
  
   not a subtype of Required type
     VV : {VV : (GHC.Ptr.Ptr <> (GHC.Word.Word32 <>)) | plen VV >= sizeOf (ptrToProxy VV)}
  
   In Context
```

**Comment by j6carey** [comment]
I reproduced the issue with what seem to be the latest commits:
```
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 22d2ea080b600a5999bfb8a053c7ee1613d0caf4
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint.git
    commit: 37955d5493ccc3bb55fbb264a9b6fb5e7f7d9c7e
  extra-dep: true
- location:
    git: https://github.com/ucsd-progsys/prover.git
    commit: b248a719bd7b2a7fa635c7b2d78bd28a2ccbf2b1
  extra-dep: true
```

**Comment by j6carey** [comment]
The indirection through `Proxy` can be eliminated:
```haskell
module T where

import Data.Word
import GHC.Ptr

{-@ class measure sizeOf :: forall a . Ptr a -> Int @-}
{-@
instance measure sizeOf :: (Ptr Word16) -> Int
sizeOf (Ptr a) = 2
@-}
{-@
instance measure sizeOf :: (Ptr Word32) -> Int
sizeOf (Ptr a) = 4
@-}

{-@
bar :: { p : Ptr Word32 | plen p >= (sizeOf p) }
    -> ()
@-}
bar :: Ptr Word32 -> ()
bar _ = ()

{-@
qux :: { p : Ptr Word32 | plen p >= 4 }
    -> ()
@-}
qux :: Ptr Word32 -> ()
qux = bar
```
```
...
**** RESULT: UNSAFE ************************************************************


 t.hs:28:7-9: Error: Liquid Type Mismatch
 
 28 | qux = bar
            ^^^
 
   Inferred type
     VV : {VV : (GHC.Ptr.Ptr GHC.Word.Word32) | plen VV >= 4}
  
   not a subtype of Required type
     VV : {VV : (GHC.Ptr.Ptr GHC.Word.Word32) | plen VV >= sizeOf VV}
  
   In Context
```

**Comment by gridaphobe** [comment]
Thanks, the issue is actually unrelated to the type ascription. There are actually two problems here:

1. We only learn measure-related facts when we see a data constructor being applied, or a case-of expression. For example, here's a simpler version of your example that still fails to type check even though it's clearly valid.
```
data Foo = Foo

{-@
measure sizeOf :: Foo -> Int
sizeOf Foo = 1
@-}

{-@ foo :: x:Foo -> {v:() | sizeOf x == 1 } @-}
foo :: Foo -> ()
foo x = ()
```

The problem here is that we never see a `Foo` pattern in the **code**, so we can't attach any `sizeOf` information to `x`. If we change `foo` to

```
foo Foo = ()
```

Then all is well. This is rather unfortunate, but I don't think there's an easy way around it without doing a case-split on `x` ourselves, which will quickly get ugly.

2. Making matters worse, your multiple instance measures for `Proxy` introduce an inconsistency, where we end up giving each `Proxy` value the type

```
Proxy :: {v:Proxy | sizeOf v == 2 && sizeOf v == 4}
```

which is unsound.

This is our fault, we shouldn't allow multiple instance measures for the same type.

**Comment by j6carey** [comment]
Sorry, I'm not quite following here.  Are `Proxy a` and `Proxy b` the same types in the view of Liquid Haskell?

Also, why does the following fail?  There is only one `sizeOf` instance:
```haskell
data Foo = Foo

{-@
class measure sizeOf :: a -> Int
@-}

{-@
instance measure sizeOf :: Foo -> Int
sizeOf Foo = 1
@-}

{-@ foo :: x:Foo -> {v:() | sizeOf x == 1 } @-}
foo :: Foo -> ()
foo Foo = ()
```
```
...
*** RESULT: ERROR *************************************************************


 t.hs:14:5: Error: Bad Type Specification
 T.foo :: x:Foo -> {v : () | sizeOf x == 1}
     Sort Error in Refinement: {v##2 : Tuple | sizeOf x == 1}
     Cannot unify a_xo with T.Foo
```

**Comment by gridaphobe** [comment]
`Proxy a` is not the same as `Proxy b` assuming `a` and `b` are fixed, but the problem is that

```
instance measure sizeOf :: (Ptr Word16) -> Int
sizeOf (Ptr a) = 2
```

gives us a type for `Ptr`

```
Ptr :: a -> {v:Ptr a | sizeOf v = 2}
```

and nothing more.

In your examples, we never see `Ptr` (constructor), so we don't get to use the type we learned from the measure.

----

In your latest example, the problem is that we don't implicitly quantify over the type variables the way GHC does. It works if you write

```
class measure sizeOf :: forall a. a -> Int
```

instead. We should fix this :)

**Comment by j6carey** [comment]
Thanks for the `forall` solution.  (I think I even ran into that before; sorry I forgot to avoid that pitfall.)

At the risk of dragging this out to much: I tried putting in more pattern matching, but that didn't completely fix the problem, perhaps because of what you said about inconsistent instance measures.  The following passes the type check unless we remove the instance for `Word16`, in which case the type check correctly fails:

```haskell
module T where

import Data.Proxy
import Data.Word
import GHC.Ptr

{-@ class measure sizeOf :: forall a . Ptr a -> Int @-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word16) -> Int
sizeOf (Ptr x) = 2
@-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word32) -> Int
sizeOf (Ptr y) = 4
@-}

{-@
bar :: { p : Ptr Word32 | plen p >= (sizeOf p) }
    -> ()
@-}
bar :: Ptr Word32 -> ()
bar (Ptr unused) = ()

{-@
qux :: { p : Ptr Word32 | plen p >= 0 }
    -> ()
@-}
qux :: Ptr Word32 -> ()
qux (Ptr addr) = bar (Ptr addr)
```

Is the measure evaluated based only upon which data constructor is invoked, and not upon the type information?

**Comment by gridaphobe** [comment]
> Is the measure evaluated based only upon which data constructor is invoked, and not upon the type information?

The measure is never "evaluated" at all, rather it's a convenient syntactic sugar for providing refinement types for data constructors. I think this is the source of your (understandable!) confusion.

Rather than deal with evaluation at the type level, as dependently typed languages do, we give refined types to data constructors, which gives us a surprising amount of expressiveness with much less complexity. So how do we turn

```
len :: [a] -> Int
len [] = 0
len (x:xs) = 1 + len xs
```

which is a function, into a set of refinement types that we can handle? It's actually quite simple, we convert each equation into a type, so

```
len [] = 0
```

becomes

```
[] :: {v:[a] | len v = 0}
```

and 

```
len (x:xs) = 1 + len xs
```

becomes

```
(:) :: x:a -> xs:[a] -> {v:[a] | len v = 1 + len xs}
```

Writing out these types by hand feels less natural than the function definition, so we provide the `measure` syntax as a simple sugar. (It's also more compositional this way because you may have multiple measures for any given type!)

Then, when we see an expression `let x = 1 : []`, we can infer that 

1. `[] :: {v:[a] | len v = 0}`, trivially by the type we extracted for `[]`, and
2. `x :: {v:[a] | len v = 1}` since the type of `:` tells us that the `len` of the result is 1 more than the `len` of the tail.

There's no evaluation :) Now, going back to your example,

```
{-@ class measure sizeOf :: forall a . Ptr a -> Int @-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word16) -> Int
sizeOf (Ptr x) = 2
@-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word32) -> Int
sizeOf (Ptr y) = 4
@-}
```

gives us two types for `Ptr`

1. `Ptr :: a -> {v:Ptr a | sizeOf v = 2}`
2. `Ptr :: a -> {v:Ptr a | sizeOf v = 4}`

we join these two types to get

```
Ptr :: a -> {v:Ptr a | sizeOf v = 2 && sizeOf v = 4}
```

which is now inconsistent and allows us to prove anything (which is why your program is deemed "safe").

We could in theory resolve the inconsistency by restricting `Ptr`s type according to the instantiation of `a`, but this would probably require some form of intersection types, so it's not likely to happen in the near future.

I hope this clarifies things a bit!

**Comment by j6carey** [comment]
If I understand you correctly, the example of generic measures in the README avoids overlapping refinements of the same data constructors because each instance of the measure mentions different data constructors, NOT because each instance mentions different types?

If so, then I think I understand, though in that case I do not know how to refine the type `Ptr a` to mean "a pointer to a region of memory large enough to hold an `a`", while retaining polymorphism in `a`.

Thanks for your help!  (And if you happen to know of a way to resolve my quandary, that would be a big plus!)

**Comment by gridaphobe** [comment]
> If I understand you correctly, the example of generic measures in the README avoids overlapping refinements of the same data constructors because each instance of the measure mentions different data constructors, NOT because each instance mentions different types?

That's exactly right!

> I do not know how to refine the type Ptr a to mean "a pointer to a region of memory large enough to hold an a", while retaining polymorphism in a.

I think we should be able to express that with the `invariant` annotation, though it's a bit of a hack...

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1458776227_6483.hs

Unfortunately, it seems that we end up with an inconsistency here too, presumably because the `invariant` generalizes `Ptr Word{16,32}` to `Ptr a`... @nikivazou is there a reason we need to do this? This would be a much easier thing to fix than modifying measures.

**Comment by nikivazou** [comment]
True, invariants are used for the generalized type constructors, so in your examples BOTH invariants apply to any `Ptr a`.  We should definitely fix that!

**Comment by j6carey** [comment]
Any idea how hard that would be?

**Comment by ranjitjhala** [comment]
@gridaphobe  and @nikivazou -- this is a very worrying soundness bug that we should fix! Why is the thing getting generalized to `Ptr a` when its clearly specified to be for two different types?

@j6carey thanks for pointing this out!

**Comment by ranjitjhala** [comment]
Yes, but we already have such a notion, c.f. measures defined like

  measure keys :: [(k, v)] -> Set k

  measure elemss :: [[a]] -> Set a

which are only applied to lists that contain, tuples, and lists
inside them, and which subsequently yield constructors that are
suitably refined.

Could this (as is getting distressingly regular) another
problem with `pruneUnsortedRefts`? Which nicely prunes out
(as the sort checking "fails") when the tycon is applied to
ANOTHER tycon (e.g. `[]` to `(,)` or `[]` respectively) but
FAILS (because the sort checking "succeeds") in this particular
case?

How is the present situation different

**Comment by gridaphobe** [comment]
The
```
measure keys :: [(k, v)] -> Set k
measure elems :: [[a]] -> Set a
```
measures are handled by `pruneUnsortedRefts` last I checked. That is, we strengthen `[]` and `(:)` with both measures and then prune the ill-sorted refts later.

I think you're right that measures should in theory be handled in the same manner as I'm suggesting for invariants, but it doesn't exist yet.

**Comment by ranjitjhala** [comment]
Just to make sure I'm not lost: the problem here had to do
with two different *measures* getting unsoundly (and unnecessarily)
conjoined, right? (The invariant thing is a side issue ...?)

```
{-@ class measure sizeOf :: forall a . Ptr a -> Int @-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word16) -> Int
sizeOf (Ptr x) = 2
@-}
{-@
instance measure sizeOf :: (Ptr Data.Word.Word32) -> Int
sizeOf (Ptr y) = 4
@-}
```

**Comment by gridaphobe** [comment]
Ack, right. I forgot about the original issue and was trying to fix the secondary issue with invariants :)

**Comment by j6carey** [comment]
I got the impression that if either invariants or measures could be made sensitive to the type information, then it might be possible to work around a lack of such sensitivity in the other feature.

My end goal is to be able to check whether a memory region is large enough based on the type of object that I expect to read from it.

**Comment by ranjitjhala** [comment]
@nikivazou or @gridaphobe -- is there any update on this? Do the above things address it? Or is this still open?

**Comment by nikivazou** [comment]
@gridaphobe are you on that or should I check it too?

**Comment by gridaphobe** [comment]
@nikivazou @ranjitjhala My fix in #657 prevents the soundness issue with overlapping instance measures, but it does not let us express @j6carey's invariant. So this is still open.

**Comment by nikivazou** [comment]
@gridaphobe the soundness issue seems to still be there

http://goto.ucsd.edu:8090/index.html#?demo=permalink%2F1461266406_7375.hs

**Comment by gridaphobe** [comment]
Ah right, there's a separate soundness issue with invariants, I only fixed the class measures.

**Comment by nikivazou** [comment]
Ok, now we support this 
 [tests/pos/MultipleInvariants.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/e4bc6c6b165fbf81f6b865ca3efa8b3fc2c1860d/tests/pos/MultipleInvariants.hs)

What else do we need to close this issue?

**Comment by gridaphobe** [comment]
It might still be nice to support measure instances that constrain the type variables, but I think that can be a separate (feature request) issue.

**Comment by nikivazou** [comment]
So, closing this with #688. 

@gridaphobe can you provide a minimum example with your feature request? Thanks!

**Comment by j6carey** [comment]
So, if I understand this correctly: rather than trying to create instances of a measure class for each type of pointer, I should define a single ordinary measure and then impose invariants on it, with each invariant being for a particular type of pointer?
